COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"
MAKEOPTS="-j2 -l2"
FEATURES="parallel-fetch candy"
CPU_FLAGS_X86="aes avx avx2 bmi1 bmi2 f16c fma3 mmx mmxext pclmul popcnt rdrand sse sse2 sse3 sse4_1 sse4_2 ssse3"

USE="${GLOBAL_FLAGS} ${DISABLED_FLAGS}"

GLOBAL_FLAGS="X alsa pulseaudio udev udisks dbus elogind networkmanager dist-kernel" 
DISABLED_FLAGS="-wayland -qt5 -qt6 -cdr -dvd -cups -bluetooth -gnome -kde"

ACCEPT_LICENSE="*"
EMERGE_DEFAULT_OPTS="--jobs 2 --load-average 2.5 --verbose --with-bdeps=y --complete-graph --backtrack=50"
INPUT_DEVICES="libinput"

L10="en"
LINGUAS="en"
LC_MESSAGES=C.UTF-8
GRUB_PLATFORMS="efi-64"
